import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {workspaceReducer as reduce, initialState, turnOverlay, validatePositions, holdingResearch} from '../src/workspaceStore.js';
const source = file => readFileSync(new URL(`../src/${file}`,import.meta.url),'utf8');
let state=initialState();
for (const route of ['/portfolio','/explore','/investigate/a']) { state=reduce(state,{type:'navigate',route}); assert.equal(state.route,route); }
state=reduce(state,{type:'open',workspace:{id:'a',model:{provider:'nim',model:'A'}}});
state=reduce(state,{type:'open',workspace:{id:'b',model:{provider:'other',model:'B'}}});
const graph={ticker:'AAA',nodes:[{node_id:'H',kind:'hypothesis'},{node_id:'C',kind:'claim'}],edges:[{edge_id:'E',source:'C',target:'H'}],followups:[{run_id:'R',delta:{added_node_ids:['C'],added_edge_ids:['E'],reassessed_hypothesis_ids:['H']}}]};
state=reduce(state,{type:'snapshot',id:'a',patch:{graph}});
assert.equal(state.workspaces[1].model.model,'B');
state=reduce(state,{type:'close',id:'b'});
assert.equal(state.workspaces[0].graph,graph);
state=reduce(state,{type:'navigate',route:'/portfolio'});
assert.equal(state.workspaces[0].model.model,'A');
assert.equal(holdingResearch(state.workspaces,'AAA','2026-01-01').length,1);
assert.deepEqual(turnOverlay(graph,'R').added_node_ids,['C']);
assert.deepEqual(turnOverlay(graph,'initial').added_node_ids,['H']);
assert.equal(turnOverlay(graph,''),null);
assert.deepEqual(initialState({getItem:()=>JSON.stringify(state)}).workspaces,state.workspaces);
assert.equal(validatePositions('AAA .6\nBBB .4').length,2);
assert.throws(()=>validatePositions('AAA .5\nAAA .5'));
assert.throws(()=>validatePositions('AAA NaN'));
assert.throws(()=>validatePositions('AAA .2'));
const app=source('App.jsx'), shell=source('WorkspaceShell.jsx'), flow=source('ClaimGraph.jsx');
assert(shell.includes('state.workspaces.map(w => <section key={w.id} hidden=')); // switched panes stay mounted
assert(app.includes('{selectedNode && <div className="inspector-drawer">'));
assert(app.includes('onClick={() => setSelectedNode(null)}'));
assert(!app.includes('selectedNode && <ClaimGraph'));
assert(app.includes('Show only new') && app.includes('Show in context'));
assert(app.includes('setTurn(e.target.value)'));
assert(flow.includes('addedEdges.has(e.id)'));
assert(flow.includes('onlyNew && delta ? [...added]'));
assert(flow.includes('claimgraph:positions:'));
assert(shell.includes("open({mode:'holding'"));
assert(shell.includes('open(state.candidate'));
assert(shell.includes('Simulate against portfolio'));
assert(shell.includes('Simulation unavailable:'));
assert(shell.includes('Unavailable: {currentAnalysis.reason}'));
assert(shell.includes('Historical simulation is descriptive evidence'));
assert.equal(reduce(state,{type:'date',value:'2020-01-01'}).candidate,null);
